# Generated by Django 5.0.6 on 2024-07-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workload',
            name='hours',
        ),
        migrations.AddField(
            model_name='workload',
            name='admin_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workload',
            name='research_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workload',
            name='teaching_hours',
            field=models.IntegerField(default=0),
        ),
    ]
