# Generated by Django 5.0.6 on 2024-07-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0002_remove_workload_hours_workload_admin_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workload',
            name='course',
        ),
        migrations.AlterField(
            model_name='workload',
            name='admin_hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workload',
            name='research_hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workload',
            name='teaching_hours',
            field=models.IntegerField(),
        ),
    ]
