# Generated by Django 5.0.6 on 2024-07-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0003_remove_workload_course_alter_workload_admin_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workload',
            name='course',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
