# Generated by Django 5.0.6 on 2024-07-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0005_alter_workload_course_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
